'app: app center': ['/src/apps/AppCenter']
'app: console': ['/src/apps/Console']
'app: organization': ['/src/apps/Organization']
'app: permissions': ['/src/apps/Permissions']
'app: agreement': ['/src/apps/Agreement']
'module: account': ['/src/components/AccountModule', '/src/ethereum-providers']
'module: onboarding': ['/src/onboarding', '/src/templates']
'module: preferences': ['/src/components/GlobalPreferences']
'security': ['/src/components/security']
